### ISSUE TITLE
Links, background image, columns

### ISSUE THREAD

**Issue by herrdeh** [Sommerregen/grav-theme-machine#6]
Sorry, more questions...

- How can I set a background image for the whole background (exept headers)? In the bootstrap.css there are too many "background-image" expressions to find the right one... ): 
- Creating a two-columns layout according to this instructions [https://learn.getgrav.org/cookbook/general-recipes#render-content-in-columns](url) does not work, because there is no partials/base.html.twig. How can I make it work?
- Links are not distingushable from other text, but I cannot find a a:link css expression. How does it work?

Cheers,
Wolf

**Comment by Sommerregen** [comment]
Hi,

to set a background image, apply it to the `body` tag and overlay the image in the header section with a white background like

```css
.header {
    background-color: white;
}
```

Instead of a `partials/base.html.twig` this theme extends from [default.html.twig](https://github.com/Sommerregen/grav-theme-machine/blob/develop/templates/default.html.twig) (see [templates/blog.html.twig#L1](https://github.com/Sommerregen/grav-theme-machine/blob/develop/templates/blog.html.twig#L1)). The contents in the `default.html.twig` can be shifted into a `partials/base.html.twig` template, but then all other "page" types have to be adjusted as well.

Links are not distinguishable because it is a setting in the bootstrap style. However you can add

```css
a {
    color: #c8305f;
    text-decoration: underline;
}
```

to the CSS file to highlight them.
